# Generated by Django 5.0.3 on 2024-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_address', models.CharField(max_length=1000)),
                ('short_link', models.CharField(max_length=100)),
            ],
        ),
    ]
